### ISSUE TITLE
ci: Unnecessary jobs for PRs

### ISSUE THREAD

**Issue by langston-barrett** [ge-high-assurance/RACK#231]
It appears that we're running both our workflows twice for every push to a pull request (see builds for `AM-HotFix` for a recent example). This is unnecessary, we should only run each workflow once per commit.

This may be related to this configuration change/discussion here: https://github.com/ge-high-assurance/RACK/pull/218#discussion_r516988526

**Comment by langston-barrett** [comment]
Some data points:

On a PR that is marked as "Draft" I observed _no_ CI builds with a configuration like this:
```yaml
on:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]
```
On that same PR, I saw the appropriate number of builds with the following configuration:
```yaml
on: [push]
```
One possible downside of this configuration is that it doesn't cause builds for pull requests from forks, but since we've never had a pull request from a fork I think this isn't a huge issue.

There is discussion online around this issue: https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/9. One of the recommendations is the following configuration:
```yaml
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
```
Unfortunately, this disables builds on pushes to other branches, so developers can't tell whether or not their changes will pass CI until they make a PR, which is suboptimal in my opinion.
