### ISSUE TITLE
UI ingestion with multiple model-graphs

### ISSUE THREAD

**Issue by kityansiu** [ge-high-assurance/RACK#979]
We have a need to ingest data that spans multiple model-graphs. Right now the UI will give the following error:
![image](https://github.com/ge-high-assurance/RACK/assets/12802455/d292e03d-e4bd-4565-9afa-e44e57a078bf)

Here's an example of the yaml files that are in this ingestion package. In ADEPT/InstanceData/import.yaml, I have the following:
```
data-graph: http://rack001/adeptdata
model-graphs:
- http://rack001/model
- http://rack001/mbsemodel
ingestion-steps:
- class: http://arcos.rack/PROV-S#ACTIVITY
  csv: ingest_ACTIVITY.csv
- class: http://arcos.rack/mbse#Engine
  csv: ingest_Engine.csv
- class: http://arcos.rack/mbse#Measurement
  csv: ingest_DesignedPartMeasurement.csv
- class: http://arcos.rack/mbse#Assembly
  csv: ingest_DesignedAssembly.csv
- class: http://arcos.rack/mbse#DesignedPart
  csv: ingest_DesignedPart.csv
- class: http://arcos.rack/REQUIREMENTS#REQUIREMENT
  csv: ingest_REQUIREMENT.csv
- class: http://arcos.rack/mbse#ManufacturedPart
  csv: ingest_Turbine.csv
- class: http://arcos.rack/mbse#Measurement
  csv: ingest_AirfoilMeasurements.csv
- class: http://arcos.rack/mbse#ManufacturedPart
  csv: ingest_Airfoil.csv
```
And in ADEPT/manifest.yaml, I have the following:

```
name: 'ADEPT Engine'
description: 'MBE Demo'
footprint:
  model-graphs:
  - http://rack001/model
  - http://rack001/mbsemodel
  data-graphs:
  - http://rack001/adeptdata
steps:
  - data: InstanceData/import.yaml
```
As an example of desired behavior, I can run `rack manifest import manifest.yaml` which correctly ingests the data into the data-graph http://rack001/adeptdata while correctly referencing both model-graphs.
